[package]
name = "p1_helloword"
version = "0.1.0"
authors = ["cyanBone <cyanbone@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
